name: Main workflow
on: [push, pull_request]

jobs:
    workflow:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.6, 3.7, 3.8]

        steps:

            - uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Cache pip
              uses: actions/cache@v1
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
                      ${{ runner.os }}-

            - name: Install dev dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -e .[dev]

            - name: Build package
              run: make build

            - name: Test package
              run: make tests
